set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g mouse on
set-option -g history-limit 100000

bind Tab move-window -r
bind q kill-pane
bind C-k kill-session

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g default-terminal "tmux-256color"

# Append, do not overwrite
set -ga terminal-overrides ",alacritty:Tc"
set -ga terminal-overrides ",xterm*:smcup@:rmcup@"

set-option -s focus-events on
set-option -s extended-keys on

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set-option -g default-shell "$SHELL"

set -g mode-keys vi

BG="#32302F"
FG="#d4be98"
set-option -g status-style bg=${BG},fg=${FG}

bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi C-j    send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi y      send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-no-clear

# OS-specific config
if-shell 'test "$(uname)" = "Darwin"' {
    source-file ~/.config/tmux/macos.conf
} {
    source-file ~/.config/tmux/linux.conf
}
